spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bootex
    username: root
    password: root123

springdoc:
  swagger-ui:
    path: /api
    groupsOrder: DESC
    operationsSorter: method
    disableSwaggerDefaultUrl: true
    displayRequestDuration: true
  apiDocs:
    path: /api-docs
  showActuator: true
  defaultConsumesMediaType: application/json
  defaultProducesMediaType: application/json


mybatis:
  mapperLocations: classpath:/mybatis/mappers/*Mapper.xml
  configLocation: classpath:/mybatis/mybatis-config.xml
